### ISSUE TITLE
Error pulling from waynr/firefox

### ISSUE THREAD

**Issue by JayKayy** [waynr/dfiles#1]
From ~/.cargo/bin after `cargo install` of firefox app. When following the instructions around `./firefox run`, I get a failure to pull waynr/firefox.

```
jkwiatko@doubu:~/.c/bin
➤ ./firefox run
Profile - ["-v", "/home/jkwiatko/.local/share/dfiles/applications/firefox/profiles/default/home/jkwiatko/.mozilla/firefox/profile:/home/jkwiatko/.mozilla/firefox/profile"]
Debian - []
firefox - []
Name - ["--name", "default"]
User: jkwiatko - []
PulseAudio - ["-v", "/home/jkwiatko/.pulse:/home/jkwiatko/.pulse", "-v", "/home/jkwiatko/.config/pulse:/home/jkwiatko/.config/pulse", "-v", "/run/user/1000/pulse:/run/user/1000/pulse"]
X11 - ["-e", "DISPLAY=unix:0", "-v", "/tmp/.X11-unix:/tmp/.X11-unix", "--device", "/dev/dri"]
Video - ["--device", "/dev/video1", "--device", "/dev/video0"]
DBus - ["-v", "/run/user/1000/bus:/run/user/1000/bus", "-v", "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket", "-v", "/home/jkwiatko/.dbus/session-bus:/home/jkwiatko/.dbus/session-bus", "-e", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus"]
Shm - ["-v", "/dev/shm:/dev/shm"]
docker run --rm -v /home/jkwiatko/.local/share/dfiles/applications/firefox/profiles/default/home/jkwiatko/.mozilla/firefox/profile:/home/jkwiatko/.mozilla/firefox/profile --name firefox-default -v /home/jkwiatko/.pulse:/home/jkwiatko/.pulse -v /home/jkwiatko/.config/pulse:/home/jkwiatko/.config/pulse -v /run/user/1000/pulse:/run/user/1000/pulse -e DISPLAY=unix:0 -v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/dri --device /dev/video1 --device /dev/video0 -v /run/user/1000/bus:/run/user/1000/bus -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket -v /home/jkwiatko/.dbus/session-bus:/home/jkwiatko/.dbus/session-bus -e DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus -v /dev/shm:/dev/shm waynr/firefox:0.1.0 /opt/firefox/firefox-bin --no-remote --profile /home/jkwiatko/.mozilla/firefox/profile
Unable to find image 'waynr/firefox:0.1.0' locally
docker: Error response from daemon: pull access denied for waynr/firefox, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```
Is there a more public image that I should be using? Or should I be pointing to my own image?

**Comment by waynr** [comment]
@JayKayy hey I didn't see this come through my inbox!

After building the binary via `cargo install` you have to then build the docker image using `./firefox build` (for other subcommands check out `./firefox -h`).

The reason this is required is that the `firefox` binary dynamically generates a `Dockerfile` (which you can see in the tarball created by `./firefox generate-archive` sub command) that creates a user in the image whose UID/GID matches your current user's UID/GID which ensures that the files created in your host system by the container via the volume mounts will be manageable by your current user.

I have a WIP branch where I am working on an alternative approach to addressing this via an entrypoint script, after which it I will begin maintaining publicly-accessible images.

Anyway, thanks for your interest and please feel welcome to ask additional questions, contribute patches, or leave feedback.
